package me.samlss.inkjet.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectDaoConfig;
    private final DaoConfig printBeanDaoConfig;
    private final DaoConfig inkAnnalDaoConfig;

    private final ProjectDao projectDao;
    private final PrintBeanDao printBeanDao;
    private final InkAnnalDao inkAnnalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        printBeanDaoConfig = daoConfigMap.get(PrintBeanDao.class).clone();
        printBeanDaoConfig.initIdentityScope(type);

        inkAnnalDaoConfig = daoConfigMap.get(InkAnnalDao.class).clone();
        inkAnnalDaoConfig.initIdentityScope(type);

        projectDao = new ProjectDao(projectDaoConfig, this);
        printBeanDao = new PrintBeanDao(printBeanDaoConfig, this);
        inkAnnalDao = new InkAnnalDao(inkAnnalDaoConfig, this);

        registerDao(Project.class, projectDao);
        registerDao(PrintBean.class, printBeanDao);
        registerDao(InkAnnal.class, inkAnnalDao);
    }
    
    public void clear() {
        projectDaoConfig.clearIdentityScope();
        printBeanDaoConfig.clearIdentityScope();
        inkAnnalDaoConfig.clearIdentityScope();
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public PrintBeanDao getPrintBeanDao() {
        return printBeanDao;
    }

    public InkAnnalDao getInkAnnalDao() {
        return inkAnnalDao;
    }

}
