package me.samlss.inkjet.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;
import org.greenrobot.greendao.annotation.Transient;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PRINT_BEAN".
 */
@Entity
public class PrintBean {

    @Id(autoincrement = true)
    private Long id;
    private String content;
    private String user_id;

    @Index
    private String project;
    private Integer state;
    private String splits;
    private Integer pieces_number;
    private Integer line_number;
    private Integer print_count;

    @Transient
    private int tmpState;

    private String title;

    @Generated
    public PrintBean() {
    }

    public PrintBean(Long id) {
        this.id = id;
    }

    @Generated
    public PrintBean(Long id, String content, String user_id, String project, Integer state, String splits, Integer pieces_number, Integer line_number, Integer print_count) {
        this.id = id;
        this.content = content;
        this.user_id = user_id;
        this.project = project;
        this.state = state;
        this.splits = splits;
        this.pieces_number = pieces_number;
        this.line_number = line_number;
        this.print_count = print_count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getSplits() {
        return splits;
    }

    public void setSplits(String splits) {
        this.splits = splits;
    }

    public Integer getPieces_number() {
        return pieces_number;
    }

    public void setPieces_number(Integer pieces_number) {
        this.pieces_number = pieces_number;
    }

    public Integer getLine_number() {
        return line_number;
    }

    public void setLine_number(Integer line_number) {
        this.line_number = line_number;
    }

    public Integer getPrint_count() {
        return print_count;
    }

    public void setPrint_count(Integer print_count) {
        this.print_count = print_count;
    }

    public int getTmpState() {
        return tmpState;
    }

    public void setTmpState(int tmpState) {
        this.tmpState = tmpState;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
