package me.samlss.inkjet.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PROJECT".
 */
@Entity
public class Project {

    @Id(autoincrement = true)
    private Long id;
    private String user_id;
    private Long generate_time;

    private String project_name;

    @Generated
    public Project() {
    }

    public Project(Long id) {
        this.id = id;
    }

    @Generated
    public Project(Long id, String user_id, Long generate_time, String project_name) {
        this.id = id;
        this.user_id = user_id;
        this.generate_time = generate_time;
        this.project_name = project_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public Long getGenerate_time() {
        return generate_time;
    }

    public void setGenerate_time(Long generate_time) {
        this.generate_time = generate_time;
    }

    public String getProject_name() {
        return project_name;
    }

    public void setProject_name(String project_name) {
        this.project_name = project_name;
    }

}
